services:
  qpa:
    build: .
    container_name: qpa
    restart: unless-stopped
    ports:
      - "8963:8963"
    volumes:
      - ./config.yaml:/QPA/config.yaml
      - ./baseprompt.json:/QPA/baseprompt.json
    environment:
      - TZ=Asia/Shanghai
